=== jackytsheng/TheBookofAnswers/schema/bible_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "book": {
      "type": "string"
    },
    "chapter": {
      "type": "integer"
    },
    "verse": {
      "type": "integer"
    },
    "language": {
      "type": "string"
    },
    "translation": {
      "type": "string"
    }
  },
  "required": [
    "book",
    "chapter",
    "id",
    "language",
    "name",
    "text",
    "translation",
    "verse"
  ]
}

=== jackytsheng/TheBookofAnswers/test_bibles/test.json
[
  {
    "id": "gn-1-1-cn-cuv",
    "name": "Genesis 1:1",
    "text": "起初，神創造天地。",
    "book": "Genesis",
    "chapter": 1,
    "verse": 1,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "gn-1-2-cn-cuv",
    "name": "Genesis 1:2",
    "text": "地是空虛混沌，淵面黑暗；神的靈運行在水面上。",
    "book": "Genesis",
    "chapter": 1,
    "verse": 2,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-23-31-cn-cuv",
    "name": "Acts 23:31",
    "text": "於是，兵丁照所吩咐他們的，將保羅夜裡帶到安提帕底。",
    "book": "Acts",
    "chapter": 23,
    "verse": 31,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-23-32-cn-cuv",
    "name": "Acts 23:32",
    "text": "第二天，讓馬兵護送，他們就回營樓去。",
    "book": "Acts",
    "chapter": 23,
    "verse": 32,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-23-33-cn-cuv",
    "name": "Acts 23:33",
    "text": "馬兵來到該撒利亞，把文書呈給巡撫，便叫保羅站在他面前。",
    "book": "Acts",
    "chapter": 23,
    "verse": 33,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-23-34-cn-cuv",
    "name": "Acts 23:34",
    "text": "巡撫看了文書，問保羅是那省的人，既曉得他是基利家人，",
    "book": "Acts",
    "chapter": 23,
    "verse": 34,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-23-35-cn-cuv",
    "name": "Acts 23:35",
    "text": "就說：等告你的人來到，我要細聽你的事；便吩咐人把他看守在希律的衙門裡。",
    "book": "Acts",
    "chapter": 23,
    "verse": 35,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-1-cn-cuv",
    "name": "Acts 24:1",
    "text": "過了五天，大祭司亞拿尼亞同幾個長老，和一個辯士帖士羅下來，向巡撫控告保羅。",
    "book": "Acts",
    "chapter": 24,
    "verse": 1,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-2-cn-cuv",
    "name": "Acts 24:2",
    "text": "保羅被提了來，帖士羅就告他說：",
    "book": "Acts",
    "chapter": 24,
    "verse": 2,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-3-cn-cuv",
    "name": "Acts 24:3",
    "text": "腓力斯大人，我們因你得以大享太平，並且這一國的弊病，因著你的先見得以更正了；我們隨時隨地滿心感謝不盡。",
    "book": "Acts",
    "chapter": 24,
    "verse": 3,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-4-cn-cuv",
    "name": "Acts 24:4",
    "text": "惟恐多說，你嫌煩絮，只求你寬容聽我們說幾句話。",
    "book": "Acts",
    "chapter": 24,
    "verse": 4,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-5-cn-cuv",
    "name": "Acts 24:5",
    "text": "我們看這個人，如同瘟疫一般，是鼓動普天下眾猶太人生亂的，又是拿撒勒教黨裡的一個頭目，",
    "book": "Acts",
    "chapter": 24,
    "verse": 5,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-6-cn-cuv",
    "name": "Acts 24:6",
    "text": "連聖殿他也想要污穢；我們把他捉住了。（有古卷在此有：要按我們的律法審問，",
    "book": "Acts",
    "chapter": 24,
    "verse": 6,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-7-cn-cuv",
    "name": "Acts 24:7",
    "text": "不料千夫長呂西亞前來，甚是強橫，從我們手中把他奪去，吩咐告他的人到你這裡來。）",
    "book": "Acts",
    "chapter": 24,
    "verse": 7,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-8-cn-cuv",
    "name": "Acts 24:8",
    "text": "你自己究問他，就可以知道我們告他的一切事了。",
    "book": "Acts",
    "chapter": 24,
    "verse": 8,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-9-cn-cuv",
    "name": "Acts 24:9",
    "text": "眾猶太人也隨著告他說：事情誠然是這樣。",
    "book": "Acts",
    "chapter": 24,
    "verse": 9,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-10-cn-cuv",
    "name": "Acts 24:10",
    "text": "巡撫點頭叫保羅說話。他就說：我知道你在這國裡斷事多年，所以我樂意為自己分訴。",
    "book": "Acts",
    "chapter": 24,
    "verse": 10,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-11-cn-cuv",
    "name": "Acts 24:11",
    "text": "你查問就可以知道，從我上耶路撒冷禮拜到今日不過有十二天。",
    "book": "Acts",
    "chapter": 24,
    "verse": 11,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-12-cn-cuv",
    "name": "Acts 24:12",
    "text": "他們並沒有看見我在殿裡，或是在會堂裡，或是在城裡，和人辯論，聳動眾人。",
    "book": "Acts",
    "chapter": 24,
    "verse": 12,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-13-cn-cuv",
    "name": "Acts 24:13",
    "text": "他們現在所告我的事並不能對你證實了。",
    "book": "Acts",
    "chapter": 24,
    "verse": 13,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-14-cn-cuv",
    "name": "Acts 24:14",
    "text": "但有一件事，我向你承認，就是他們所稱為異端的道，我正按著那道事奉我祖宗的神，又信合乎律法的和先知書上一切所記載的，",
    "book": "Acts",
    "chapter": 24,
    "verse": 14,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-15-cn-cuv",
    "name": "Acts 24:15",
    "text": "並且靠著神，盼望死人，無論善惡，都要復活，就是他們自己也有這個盼望。",
    "book": "Acts",
    "chapter": 24,
    "verse": 15,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-16-cn-cuv",
    "name": "Acts 24:16",
    "text": "我因此自己勉勵，對神對人，常存無虧的良心。",
    "book": "Acts",
    "chapter": 24,
    "verse": 16,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-17-cn-cuv",
    "name": "Acts 24:17",
    "text": "過了幾年，我帶著賙濟本國的捐項和供獻的物上去。",
    "book": "Acts",
    "chapter": 24,
    "verse": 17,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-18-cn-cuv",
    "name": "Acts 24:18",
    "text": "正獻的時候，他們看見我在殿裡已經潔淨了，並沒有聚眾，也沒有吵嚷，惟有幾個從亞西亞來的猶太人。",
    "book": "Acts",
    "chapter": 24,
    "verse": 18,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-19-cn-cuv",
    "name": "Acts 24:19",
    "text": "他們若有告我的事，就應當到你面前來告我。",
    "book": "Acts",
    "chapter": 24,
    "verse": 19,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-20-cn-cuv",
    "name": "Acts 24:20",
    "text": "即或不然，這些人若看出我站在公會前，有妄為的地方，他們自己也可以說明。",
    "book": "Acts",
    "chapter": 24,
    "verse": 20,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-21-cn-cuv",
    "name": "Acts 24:21",
    "text": "縱然有，也不過一句話，就是我站在他們中間大聲說：我今日在你們面前受審，是為死人復活的道理。",
    "book": "Acts",
    "chapter": 24,
    "verse": 21,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-22-cn-cuv",
    "name": "Acts 24:22",
    "text": "腓力斯本是詳細曉得這道，就支吾他們說：且等千夫長呂西亞下來，我要審斷你們的事。",
    "book": "Acts",
    "chapter": 24,
    "verse": 22,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-23-cn-cuv",
    "name": "Acts 24:23",
    "text": "於是吩咐百夫長看守保羅，並且寬待他，也不攔阻他的親友來供給他。",
    "book": "Acts",
    "chapter": 24,
    "verse": 23,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-24-cn-cuv",
    "name": "Acts 24:24",
    "text": "過了幾天，腓力斯和他夫人─猶太的女子土西拉─一同來到，就叫了保羅來，聽他講論信基督耶穌的道。",
    "book": "Acts",
    "chapter": 24,
    "verse": 24,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-25-cn-cuv",
    "name": "Acts 24:25",
    "text": "保羅講論公義、節制，和將來的審判。腓力斯甚覺恐懼，說：你暫且去罷，等我得便再叫你來。保羅講論公義、節制，和將來的審判。腓力斯甚覺恐懼，說：你暫且去罷，等我得便再叫你來。",
    "book": "Acts",
    "chapter": 24,
    "verse": 25,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-26-cn-cuv",
    "name": "Acts 24:26",
    "text": "腓力斯又指望保羅送他銀錢，所以屢次叫他來，和他談論。",
    "book": "Acts",
    "chapter": 24,
    "verse": 26,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-24-27-cn-cuv",
    "name": "Acts 24:27",
    "text": "過了兩年，波求非斯都接了腓力斯的任；腓力斯要討猶太人的喜歡，就留保羅在監裡。",
    "book": "Acts",
    "chapter": 24,
    "verse": 27,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-1-cn-cuv",
    "name": "Acts 25:1",
    "text": "非斯都到了任，過了三天，就從該撒利亞上耶路撒冷去。",
    "book": "Acts",
    "chapter": 25,
    "verse": 1,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-2-cn-cuv",
    "name": "Acts 25:2",
    "text": "祭司長和猶太人的首領向他控告保羅，",
    "book": "Acts",
    "chapter": 25,
    "verse": 2,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-3-cn-cuv",
    "name": "Acts 25:3",
    "text": "又央告他，求他的情，將保羅提到耶路撒冷來，他們要在路上埋伏殺害他。",
    "book": "Acts",
    "chapter": 25,
    "verse": 3,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-4-cn-cuv",
    "name": "Acts 25:4",
    "text": "非斯都卻回答說：保羅押在該撒利亞，我自己快要往那裡去；",
    "book": "Acts",
    "chapter": 25,
    "verse": 4,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-5-cn-cuv",
    "name": "Acts 25:5",
    "text": "又說：你們中間有權勢的人與我一同下去，那人若有甚麼不是，就可以告他。",
    "book": "Acts",
    "chapter": 25,
    "verse": 5,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-6-cn-cuv",
    "name": "Acts 25:6",
    "text": "非斯都在他們那裡住了不過十天八天，就下該撒利亞去；第二天坐堂，吩咐將保羅提上來。",
    "book": "Acts",
    "chapter": 25,
    "verse": 6,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "act-25-7-cn-cuv",
    "name": "Acts 25:7",
    "text": "保羅來了，那些從耶路撒冷下來的猶太人周圍站著，將許多重大的事控告他，都是不能證實的。",
    "book": "Acts",
    "chapter": 25,
    "verse": 7,
    "language": "cn",
    "translation": "cuv"
  },
  {
    "id": "re-22-16-cn-cuv",
    "name": "Revelation 22:16",
    "text": "我─耶穌差遣我的使者為眾教會將這些事向你們證明。我是大衛的根，又是他的後裔。我是明亮的晨星。",
    "book": "Revelation",
    "chapter": 22,
    "verse": 16,
    "language": "cn",
    "translation": "cuv"
  }
]
